# Generated by Django 4.2.7 on 2026-02-20 17:55

import detection.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('response', models.TextField()),
                ('language', models.CharField(default='en', max_length=5)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(default=detection.models.generate_patient_id, max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=1)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detection_id', models.CharField(default=detection.models.generate_detection_id, max_length=50, unique=True)),
                ('image', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
                ('predicted_disease', models.CharField(max_length=100)),
                ('confidence_score', models.FloatField()),
                ('severity', models.CharField(choices=[('MILD', 'Mild'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe')], max_length=10)),
                ('english_explanation', models.TextField(blank=True)),
                ('tamil_explanation', models.TextField(blank=True)),
                ('symptoms', models.TextField(blank=True)),
                ('causes', models.TextField(blank=True)),
                ('treatment', models.TextField(blank=True)),
                ('prevention', models.TextField(blank=True)),
                ('disclaimer', models.TextField(blank=True)),
                ('report_pdf', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('detection_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('all_probabilities', models.TextField(blank=True, default='{}')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='detection.patient')),
            ],
            options={
                'ordering': ['-detection_date'],
            },
        ),
    ]
